const RAW_EXTENSION = "CR3";
const SIDECAR_EXTENSION = "nlp.json";
const NLP_VERSION = "3.0.2";
const NLP_PROPERTY_MATCH = "nlp%";

const CONSTANTS = {
  NLP_PROPERTY_MATCH,
  NLP_VERSION,
  RAW_EXTENSION,
  SIDECAR_EXTENSION,
};

export { CONSTANTS };
